### ISSUE TITLE
Obtanium not getting .png and .app

### ISSUE THREAD

**Issue by Lucidic15** [schattenphoenix/es_applauncher#2]
I have selected on the app specifically to extract and it will not.

**Comment by Lucidic15** [comment]
Oh? the select on an app is "Exclude", this should at least be labeled. I thought it was to only grab those apps selected.

**Comment by Lucidic15** [comment]
Ohhh. STILL Wrong lol, its to mark which are games. 

THOUGH, regardless Obtanium is still not showing up anywhere for .app or .png.

**Comment by schattenphoenix** [comment]
Could you elaborate?
Obtanium can only fetch apk files I thought?
The zip I offer bundles the .xml files on top.
.app and .png files need to be generated on the device from the apps you have installed.

The "disable" and "mark as game" are not labeled yet, cause I just quickly added it, but it is documented in the readme and patch notes.

**Comment by Lucidic15** [comment]
Thanks for elaborating on the label.

Doesnt matter what Obtanium does within the app. 

But your app will not grab the .app or .png for it for me so I can access it from ES-DE is what I am saying.

**Comment by Lucidic15** [comment]
Ohh, you click the app to disable, and the checkbox is the mark as game. This resolves it.
