### ISSUE TITLE
Custom System Icons

### ISSUE THREAD

**Issue by punker180** [schattenphoenix/es_applauncher#3]
thanks so much for putting this together its made things so much easier. my main question is how would i create icons for the custom systems themselves? i was able to get covers for the android apps and games working pretty straight forward. but im using the Linear theme (default theme) with ES-DE and when i get to Android games as the example its just text "android games" i would like to replace that with like the little green android guy or something. that goes for GBAH and SNESH but cant find any clear documentation on how to do that. thanks for your time on this!

**Comment by schattenphoenix** [comment]
> thanks so much for putting this together its made things so much easier. my main question is how would i create icons for the custom systems themselves? i was able to get covers for the android apps and games working pretty straight forward. but im using the Linear theme (default theme) with ES-DE and when i get to Android games as the example its just text "android games" i would like to replace that with like the little green android guy or something. that goes for GBAH and SNESH but cant find any clear documentation on how to do that. thanks for your time on this!

This is a question that's better suited for the theme in question.
In the es launcher you can choose what subfolder it goes into (default is covers), some themes need a different media folder tho, covers and marquees is used for art book next and its variants for example.

I don't know what's needed for the linear theme tho.

My suggestion would be to join the es-de discord and ask there in the theme channel, most theme devs are actually active there or you ask on the GitHub of said theme 👍

**Comment by schattenphoenix** [comment]
I'll close this, seems like there is no more interest
