### ISSUE TITLE
Doesn't Work For Android 10

### ISSUE THREAD

**Issue by DroidlyMobile** [schattenphoenix/es_applauncher#4]
This won't work on Android 10 devices haven't tried anything lower but when I select my scoped storage path it doesn't create the folder paths like it does on Android 11 +.

**Comment by schattenphoenix** [comment]
> This won't work on Android 10 devices haven't tried anything lower but when I select my scoped storage path it doesn't create the folder paths like it does on Android 11 +.

Now that I have access to another device, I'll try it,  but sadly scoped storage is pretty complicated :(

**Comment by DroidlyMobile** [comment]
Is the source code available not trying to rip you off but scoped storage is only as complicated as you make it, but technically it's been around for a long time.  You might find it helpful to copy source folders to the URI path directly after they select the game paths.  I only tried with the Odin 1 Pro if that helps.

**Comment by schattenphoenix** [comment]
It's not currently available. 
The issue is mostly the Android versions where scoped storage was still young. 
I'm using flutter and the API should be working on A10 so I'll need to check when I have time. 
Potentially later today.

**Comment by DroidlyMobile** [comment]
Alright no worries I just wanted to let you know that is all otherwise my
other devices this is great!

**Comment by schattenphoenix** [comment]
> Alright no worries I just wanted to let you know that is all otherwise my other devices this is great!

Could you maybe try with the newest release?
I tested it on my Odin 1 Pro and it works without issues.
Still complains in debug log about the permission not existing (MANAGE_EXTERNAL_STORAGE) but I left the request in there for A14.
It shouldn't have any impact on use tho.

**Comment by schattenphoenix** [comment]
Closing for lack of feedback

**Comment by amit27592** [comment]
It doesn't work for my Android 10 device either.
Here's the exception:

```
06-27 20:56:40.438 15551 15577 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathAccessException: Creation failed, path = '/storage/emulated/0/ES-DE/androidapps' (OS Error: Permission denied, errno = 13)
06-27 20:56:40.438 15551 15577 E flutter : #0      _checkForErrorResponse (dart:io/common.dart:55)
06-27 20:56:40.438 15551 15577 E flutter : #1      _Directory.create.<anonymous closure> (dart:io/directory_impl.dart:109)
06-27 20:56:40.438 15551 15577 E flutter : <asynchronous suspension>
06-27 20:56:40.438 15551 15577 E flutter : #2      _MyHomePageState._saveAppFiles (package:es_applauncher/main.dart:147)
06-27 20:56:40.438 15551 15577 E flutter : <asynchronous suspension>
06-27 20:56:40.438 15551 15577 E flutter : 
```

**Comment by amit27592** [comment]
If you want to share an apk with additional logging etc to help you debug, I'm happy to help.

**Comment by schattenphoenix** [comment]
> It doesn't work for my Android 10 device either. Here's the exception:
> 
> ```
> 06-27 20:56:40.438 15551 15577 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathAccessException: Creation failed, path = '/storage/emulated/0/ES-DE/androidapps' (OS Error: Permission denied, errno = 13)
> 06-27 20:56:40.438 15551 15577 E flutter : #0      _checkForErrorResponse (dart:io/common.dart:55)
> 06-27 20:56:40.438 15551 15577 E flutter : #1      _Directory.create.<anonymous closure> (dart:io/directory_impl.dart:109)
> 06-27 20:56:40.438 15551 15577 E flutter : <asynchronous suspension>
> 06-27 20:56:40.438 15551 15577 E flutter : #2      _MyHomePageState._saveAppFiles (package:es_applauncher/main.dart:147)
> 06-27 20:56:40.438 15551 15577 E flutter : <asynchronous suspension>
> 06-27 20:56:40.438 15551 15577 E flutter : 
> ```

Did you get a request for permission?
On my Odin 1 Pro it works, that's the closest device I have to test.

**Comment by amit27592** [comment]
Yes, I did get a request for permission.
This is on Android 10 on the Nintendo Switch.

**Comment by JacobBrown4** [comment]
FWIW I found this because I was having issues with this not working on Android 12 (Specifically GammaOS v1.51 on the RG405m). I managed to fix it by going to the app info for ES Applauncher and changing the file and media permission from 'Allow access to media only' to 'Allow management of all files'.

After that it was able to generate the files successfully. Unsure if that solution will work for lower Android versions but just throwing it out there.

**Comment by schattenphoenix** [comment]
> FWIW I found this because I was having issues with this not working on Android 12 (Specifically GammaOS v1.51 on the RG405m). I managed to fix it by going to the app info for ES Applauncher and changing the file and media permission from 'Allow access to media only' to 'Allow management of all files'.
> 
> After that it was able to generate the files successfully. Unsure if that solution will work for lower Android versions but just throwing it out there.

This is interesting cause it should request that on first launch
Sadly it's impossible to debug this on every device
On my Odin 2 it requests the permission and if I accept,  it works
The same on my Odin 1 pro and my xiaomi 11 ultra with Android 14

**Comment by thomas-deliot** [comment]
> FWIW I found this because I was having issues with this not working on Android 12 (Specifically GammaOS v1.51 on the RG405m). I managed to fix it by going to the app info for ES Applauncher and changing the file and media permission from 'Allow access to media only' to 'Allow management of all files'.
> 
> After that it was able to generate the files successfully. Unsure if that solution will work for lower Android versions but just throwing it out there.

You just saved me after half an hour of headache ! I just got the exact same device, running GammaOS 1.51 as well, and ES applauncher wasn't creating any .app files anywhere. After changing what you said it did. Thanks !
