### ISSUE TITLE
androidapps

### ISSUE THREAD

**Issue by KoB-Kirito** [schattenphoenix/es_applauncher#8]
There is support for androidapps. There is a folder, the theme even has an image for it.

I can move apps from games over manually and it works fine, but everytime I have to add something new, es_applauncher breaks everything again.

Can you add a checkbox for apps too please?

![image](https://github.com/user-attachments/assets/e2480ef0-018a-4d84-88fb-37ae98cc28ee)

**Comment by schattenphoenix** [comment]
> There is support for androidapps. There is a folder, the theme even has an image for it.
> 
> I can move apps from games over manually and it works fine, but everytime I have to add something new, es_applauncher breaks everything again.
> 
> Can you add a checkbox for apps too please?
> 
> ![image](https://private-user-images.githubusercontent.com/51691757/358779191-e2480ef0-018a-4d84-88fb-37ae98cc28ee.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NTQ1NDcsIm5iZiI6MTcyMzg1NDI0NywicGF0aCI6Ii81MTY5MTc1Ny8zNTg3NzkxOTEtZTI0ODBlZjAtMDE4YS00ZDg0LTg4ZmItMzdhZTk4Y2MyOGVlLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QwMDI0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDNhM2VjNDQ2ODAxMDZhMTVjMTQ1Njc3N2U1NjkzZWIyZTMxZTEzOGVhMTI5ODUwZjYyMGEyNDYxNWU5MTU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JI-kNzn_m0gvanFfXqSa6pgt8SSjVWWN1hLBoM5TFIc)

I don't understand
If you check no checkbox it will put it in androidapps?

**Comment by KoB-Kirito** [comment]
Ahh, that's how that works 🤦🏻‍♂️

Never occured to me to check no checkbox at all, so never happened that anything got put in androidapps..

Maybe replace the disable checkboxes with App and disable apps that have no checkbox checked. Would make more sense imho.

**Comment by schattenphoenix** [comment]
Originally there was no check boxes
There was only a list cause only apps existed (we added it manually).
Then I added a disable on request, that's why it looks like this.

**Comment by KoB-Kirito** [comment]
I see. I'm just saying that it would be more logical now if every function was linked to an option.
If I do nothing with an entry and then nothing is done with it, that would be easier to understand. At least that was not clear to me. It feels like a hidden function. Not consistent.

**Comment by schattenphoenix** [comment]
I get that
Most people I've talked to about it basically were with me from the beginning so it makes sense for us lol. 

I was actually hoping to not need to update it anymore cause the functionality will be integrated in ES-DE, but I don't know a time frame so it could be tomorrow, could be next year. 

I might change it or at least clarify it in readme.
Once I'm home next week

**Comment by KoB-Kirito** [comment]
If it gets integrated, it should be clear there though.

**Comment by schattenphoenix** [comment]
> If it gets integrated, it should be clear there though.

I agree but it's a minor thing
If I have time to change it, I might do so in the near future. 

Since your issue was fixed, do you mind closing the issue?
